name: ECS Workflow
on: 
  push:
    branches: 
      - ECR_Pipeline_Test
      - main
    paths:
      - 'ECR_Container_Test/**'
  workflow_dispatch:
  
jobs:
  ECR-Second:
    runs-on: unbuntu-latest
    steps:
      - name : testing
        run: ls
