name: ECS Workflow
on: 
  push:
    branches: 
      - ECR_Pipeline_Test
      - main
    paths:
      - 'ECR_Container_Test/**'
  workflow_dispatch:
  
jobs:
  ECR-Deployment:
    runs-on: unbuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          repository: mtafsir/LambdaTerraformPipeline
          token: ${{ secrets.PAT }}
          ref: main
      - name : test 
        run: ls
