name: Workflow 1
on: 
  push:
    branches: 
      - ECR_Pipeline_Test
      - main
    paths:
      - 'ECR_Container_Test/**'
  workflow_dispatch:
  
jobs:
  ECR-Second:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        if: "startsWith('${{ GITHUB_REF }}', 'src/')"
        with:
          repository: mtafsir/ECR_Pipeline_Test
          token: ${{ secrets.PAT }}
          ref: ECR_Pipeline_Test
      - name : testing
        run: ls


