name: ECR_Apply
on: 
  push:
    branches: 
      - New_ECS
      - main
    paths:
      - 'ECR_Container_Test/**'
      - "Terraform/**"
  workflow_dispatch:
  
jobs:


  # ECR Sandbox deployment
  ECR_Production_Push:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/New_ECS' }}
    steps:

      # Download the repository in concern
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          repository: mtafsir/ECR_Pipeline_Test
          token: ${{ secrets.PAT }}
          ref: New_ECS
      
      - name : testing
        run: cd Terraform/ECS_Test
      - name: testing 2  
        run: ls

      # Configure AWS Credentials  
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Deploy image to AWS
      
      # Terraform Commands
      - name: Terraform fmt
        id: fmt
        working-directory: Terraform/ECS_Test
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        working-directory: Terraform/ECS_Test
        run: terraform init

      - name: Terraform Validate
        id: validate
        working-directory: Terraform/ECS_Test
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        working-directory: Terraform/ECS_Test
        run: terraform plan -no-color
        continue-on-error: true


      - name: Terraform Apply
        id: Apply
        working-directory: Terraform/ECS_Test
        run: terraform apply -auto-approve

  # ECR Prod deployment
  ECR_Sandbox_Push:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/New_ECS' }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          repository: mtafsir/ECR_Pipeline_Test
          token: ${{ secrets.PAT }}
          ref: New_ECS
      - name : testing
        run: ls

    # PR Comments