name: Workflow 1
on: 
  push:
    branches: 
      - New_ECS
      - main
    paths:
      - 'ECR_Container_Test/**'
  workflow_dispatch:
  
jobs:
  ECR-Second:
    runs-on: ubuntu-latest
    if: "startsWith('${{ github.ref_name }}', 'New_ECS')"
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          repository: mtafsir/ECR_Pipeline_Test
          token: ${{ secrets.PAT }}
          ref: New_ECS
      - name : testing
        run: ls


