name: ECS Workflow
on: 
  push:
    branches: [New_ECS]
  workflow_dispatch:
  
jobs:
  ECR-Deployment:
    runs-on: ubuntu-latest
    steps:
      - name: google Monitoring
        uses: ./Project_1/Production/main.yml

